# Generated by Django 5.2.2 on 2025-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("payment", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("quote", "Quote"),
                            ("expense", "Expense"),
                            ("customer", "Customer"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
